import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const pipelineRuns = sqliteTable("pipeline_runs", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  startedAt: text("started_at").notNull(),
  finishedAt: text("finished_at"),
  source: text("source"),
  status: text("status").notNull().default("running"),
  downloaded: integer("downloaded"),
  tldFiltered: integer("tld_filtered"),
  keywordFiltered: integer("keyword_filtered"),
  randomInserted: integer("random_inserted"),
  inserted: integer("inserted"),
  geoUs: integer("geo_us"),
  geoNonUs: integer("geo_non_us"),
  geoFailed: integer("geo_failed"),
  siteProcessed: integer("site_processed"),
  matched: integer("matched"),
  siteNotOutdoor: integer("site_not_outdoor"),
  sitePendingRetry: integer("site_pending_retry"),
  randomProcessed: integer("random_processed"),
  randomMatched: integer("random_matched"),
  keywordProcessed: integer("keyword_processed"),
  keywordMatched: integer("keyword_matched"),
  expired: integer("expired"),
  error: text("error"),
  pipelineVersion: text("pipeline_version"),
});

export type PipelineRun = typeof pipelineRuns.$inferSelect;

export const domains = sqliteTable("domains", {
  domain: text("domain").primaryKey(),
  sourceDate: text("source_date"),
  firstSeenAt: text("first_seen_at").notNull(),
  lastSeenAt: text("last_seen_at").notNull(),
  expiresAt: text("expires_at"),
  status: text("status").notNull(),
  resolvedIp: text("resolved_ip"),
  countryCode: text("country_code"),
  websiteUrl: text("website_url"),
  location: text("location"),
  attemptCount: integer("attempt_count").notNull().default(0),
  lastCheckedAt: text("last_checked_at"),
  nextCheckAt: text("next_check_at"),
  lastHttpStatus: integer("last_http_status"),
  lastError: text("last_error"),
  classificationReason: text("classification_reason"),
  classifiedAt: text("classified_at"),
  established: text("established"),
  isTemplate: integer("is_template", { mode: "boolean" }).notNull().default(false),
  score: integer("score"),
  scoreCategory: text("score_category"),
  redirectedTo: text("redirected_to"),
  redirectDomain: text("redirect_domain"),
  phone: text("phone"),
  email: text("email"),
  ecomOnly: integer("ecom_only", { mode: "boolean" }).notNull().default(false),
  emailSentAt: text("email_sent_at"),
  humanReviewed: integer("human_reviewed", { mode: "boolean" }).notNull().default(false),
  humanVerdict: text("human_verdict"),
  humanReviewNotes: text("human_review_notes"),
  starred: integer("starred", { mode: "boolean" }).notNull().default(false),
  ownerName: text("owner_name"),
  fullAddress: text("full_address"),
  enrichedAt: text("enriched_at"),
  businessSummary: text("business_summary"),
  businessSize: text("business_size"),
  employeeEstimate: text("employee_estimate"),
  locationCount: text("location_count"),
  entityType: text("entity_type"),
  socialLinks: text("social_links"),
  sideProject: integer("side_project", { mode: "boolean" }).notNull().default(false),
  longevity: text("longevity"),
  auditNotes: text("audit_notes"),
  auditVerdict: text("audit_verdict"),
  foundVersion: text("found_version"),
  classifiedVersion: text("classified_version"),
  enrichedVersion: text("enriched_version")
});

export type Domain = typeof domains.$inferSelect;
